### ISSUE TITLE
[Chrome 73+] Uncaught SyntaxError: Invalid destructuring assignment target

### ISSUE THREAD

**Issue by t2ym** [t2ym/thin-hook#288]
[Chrome 73+] Uncaught SyntaxError: Invalid destructuring assignment target

## Reproducible Code
```javascript
// lhs.js - non-hooked version works fine
{
  with ({}) {
    var wv1 = {}, wv2 = [9];
    [wv5 = wv1 /* error when hooked */, ...wv6] = [wv1 = 1, ...wv2];
  }
}
```
```javascript
// lhs.js - hooked version (extracted)
      [__hook__('w.=', __with__, [
          'wv5',
          {
            set ['='](v) {
              wv5 = v;
            },
            get ['=']() {
              return wv5;
            }
          }
        ], __context_mapper__[19], false)['='] = __hook__('w.', __with__, [
          'wv1',
          () => wv1
        ], __context_mapper__[19], false), ...(__hook__('w.=', __with__, [
          'wv6',
          {
            set ['='](v) {
              wv6 = v;
            },
            get ['=']() {
              return wv6;
            }
          }
        ], __context_mapper__[19], false))['=']] = [
        __hook__('w=', __with__, [
          'wv1',
          1,
          v => wv1 = v
        ], __context_mapper__[19], false),
        ...__hook__('w.', __with__, [
          'wv2',
          () => wv2
        ], __context_mapper__[19], false)
      ];
```

## Non reproducible code
```javascript
// lhs.js - non-hooked version
{
  with ({}) {
    var wv1 = {}, wv2 = [9];
    [wv5 /* = wv1 // commenting out this assignment works around the issue */, ...wv6] = [wv1 = 1, ...wv2];
  }
}
```

## Notes
- Not reproducible with Chrome 72
- Not reproducible with Firefox 66

**Comment by t2ym** [comment]
`wct` failures due to the issue

```
installing and starting Selenium server for local browsers
Selenium server running on port 44727
chrome 74                Beginning tests via http://localhost:8081/components/thin-hook/generated-index.html?cli_browser_id=0
chrome failed to maximize
firefox 67               Beginning tests via http://localhost:8081/components/thin-hook/generated-index.html?cli_browser_id=1
chrome 74                ✖ test/basic/basic-test.html » thin-hook basic tests » Raw calls of hook() API » ArrayPattern ArrayPattern  { with ({}) { let a,b,c,d,e = {}; [a, b = a, [c], {_d: d}, e.p] = [1, 2, [3], {_d:4}, 5]; [a,b,c,d,e.p]; } } { with ({}) { let a,b,c,d,e = {}; [a, b = a, [c], {_d: d}, e.p] = [1, 2, [3], {_d:4}, 5]; [a,b,c,d,e.p]; } }

  Invalid destructuring assignment target
    <unknown> at     HookApi.operation at basic-test.js:2267:0
    <unknown> at   Context.<anonymous> at /components/scenarist/Suite.js:495:0

chrome 74                ✖ test/basic/basic-test.html » thin-hook basic tests » Raw calls of hook() API » ObjectPattern ObjectPattern  { with ({}) { let a,b,c,d,f,o; ({ _a: a, _b: b = a, c, _d: [d], _e: { _f: f }, _g: o } = { _a: 1, _b: 2, c: 3, _d: [4], _e: {_f: 5}, _g: 6 }); [a,b,c,d,f,o]; } } { with ({}) { let a,b,c,d,f,o; ({ _a: a, _b: b = a, c, _d: [d], _e: { _f: f }, _g: o } = { _a: 1, _b: 2, c: 3, _d: [4], _e: {_f: 5}, _g: 6 }); [a,b,c,d,f,o]; } }

  Invalid destructuring assignment target
    <unknown> at     HookApi.operation at basic-test.js:2267:0
    <unknown> at   Context.<anonymous> at /components/scenarist/Suite.js:495:0

chrome 74                Tests failed: 2 failed tests
firefox 67               Tests passed
Test run ended in failure: 2 failed tests

chrome 74 (361/0/2)                     firefox 67 (363/0/0)                  


Error: 2 failed tests

```

**Comment by t2ym** [comment]
## Not Reproducible with Chrome 79.0.3945.88
- `wct` passes with no errors
- To be closed after further verification
