### ISSUE TITLE
[NPM] 0.4.0-alpha.22 cannot be published on NPM "PUT https://registry.npmjs.org/thin-hook - Not found"

### ISSUE THREAD

**Issue by t2ym** [t2ym/thin-hook#364]
## NPM debug log

```
15 notice === Tarball Details ===
16 notice name:          thin-hook
16 notice version:       0.4.0-alpha.22
16 notice package size:  41.2 MB
16 notice unpacked size: 123.4 MB
16 notice shasum:        d167d777a64cd49533501859cea0ff05590d18b4
16 notice integrity:     sha512-rX+e4ZaVC4L9B[...]HfK80kjVlIBSw==
16 notice total files:   3098
17 notice
18 http fetch PUT 404 https://registry.npmjs.org/thin-hook 10073ms
19 verbose stack Error: 404 Not Found - PUT https://registry.npmjs.org/thin-hook - Not found
19 verbose stack     at /home/t2ym/.nvm/versions/node/v12.16.1/lib/node_modules/npm/node_modules/npm-registry-fetch/check-response.js:104:15
19 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:97:5)
20 verbose statusCode 404
21 verbose pkgid thin-hook@0.4.0-alpha.22
22 verbose cwd /home/t2ym/work/components/tmp/domintrusion/thin-hook
23 verbose Linux 5.4.0-42-generic
24 verbose argv "/home/t2ym/.nvm/versions/node/v12.16.1/bin/node" "/home/t2ym/.nvm/versions/node/v12.16.1/bin/npm" "publish"
25 verbose node v12.16.1
26 verbose npm  v6.14.4
27 error code E404
28 error 404 Not Found - PUT https://registry.npmjs.org/thin-hook - Not found
29 error 404
30 error 404 'thin-hook@0.4.0-alpha.22' is not in the npm registry.
31 error 404 You should bug the author to publish it (or use the name yourself!)
32 error 404 Note that you can also install from a
33 error 404 tarball, folder, http url, or git url.
34 verbose exit [ 1, true ]
```

**Comment by t2ym** [comment]
Do I have to eliminate all dependencies with vulnerabilities?

**Comment by t2ym** [comment]
Is this notification on the demo keys related?

[t2ym/thin-hook] Generic Private Key apikey exposed on GitHub

**Comment by t2ym** [comment]
Is the package too big to publish on NPM?  I can remove `demo-frontend/` to make the package smaller

**Comment by t2ym** [comment]
Contacting NPM support.

**Comment by t2ym** [comment]
Reproducible with 0.4.0-alpha.23 as well

**Comment by t2ym** [comment]
`.npmrc` was broken
fixed after `npm adduser`
