### ISSUE TITLE
[test][SauceLabs][coverage] Test on Sauce Labs stalls with instrumented hook.min.js

### ISSUE THREAD

**Issue by t2ym** [t2ym/thin-hook#66]
[test][SauceLabs][coverage] Test on Sauce Labs stalls with instrumented hook.min.js

**Comment by t2ym** [comment]
WebSocket connection from Sauce Labs is failing.  No fallback to HTTP Polling is observed.

**Comment by t2ym** [comment]
WCT - socket.io server - Tunneled Internet - squid in Sauce Labs - socket.io client - WCT browser.js

socket.io server detects __closing of TCP connection__ for a HTTP polling socket.io transport, although socket.io client in the browser never triggers closing it.
It seems the squid proxy in Sauce Labs unexpectedly disconnects the keep-alive HTTP session via the proxy.
What triggers the TCP disconnection?

The subsequent socket.io payloads from the client, which assumes the socket.io session is still alive, are dismissed with "Session ID unknown" error as the session has already been closed on the TCP disconnection.

```
Transport.onError undefined Error
    at XHR.Transport.onError (/home/fedora/WebComponents/components/thin-hook/node_modules/engine.io/lib/transport.js:91:55)
    at IncomingMessage.onClose (/home/fedora/WebComponents/components/thin-hook/node_modules/engine.io/lib/transports/polling.js:98:10)
    at emitNone (events.js:105:13)
    at IncomingMessage.emit (events.js:207:7)
    at abortIncoming (_http_server.js:406:9)
    at socketOnClose (_http_server.js:399:3)
    at emitOne (events.js:120:20)
    at Socket.emit (events.js:210:7)
    at TCP._handle.close [as _onclose] (net.js:548:12)
close delete clients[SW7YFRavrIdQ5zdMAAAA]
close Error
    at Socket.<anonymous> (/home/fedora/WebComponents/components/thin-hook/node_modules/engine.io/lib/server.js:311:26)
    at Object.onceWrapper (events.js:318:30)
    at emitTwo (events.js:130:20)
    at Socket.emit (events.js:213:7)
    at Socket.onClose (/home/fedora/WebComponents/components/thin-hook/node_modules/engine.io/lib/socket.js:311:10)
    at Socket.onError (/home/fedora/WebComponents/components/thin-hook/node_modules/engine.io/lib/socket.js:120:8)
    at Object.onceWrapper (events.js:316:30)
    at emitOne (events.js:115:13)
    at XHR.emit (events.js:210:7)
    at XHR.Transport.onError (/home/fedora/WebComponents/components/thin-hook/node_modules/engine.io/lib/transport.js:92:10)
Transport.onError undefined Error
    at XHR.Transport.onError (/home/fedora/WebComponents/components/thin-hook/node_modules/engine.io/lib/transport.js:91:55)
    at IncomingMessage.onClose (/home/fedora/WebComponents/components/thin-hook/node_modules/engine.io/lib/transports/polling.js:152:10)
    at emitNone (events.js:105:13)
    at IncomingMessage.emit (events.js:207:7)
    at abortIncoming (_http_server.js:406:9)
    at socketOnClose (_http_server.js:399:3)
    at emitOne (events.js:120:20)
    at Socket.emit (events.js:210:7)
    at TCP._handle.close [as _onclose] (net.js:548:12)
sendErrorMessage /socket.io/?EIO=3&transport=polling&t=LsXitkT&sid=SW7YFRavrIdQ5zdMAAAA Session ID unknown
```

**Comment by t2ym** [comment]
If the socket.io payloads are sent one by one, the issue disappears on Firefox while it is still reproducible on Chrome.

**Comment by t2ym** [comment]
## Experimental Fix with the following fix
https://github.com/t2ym/web-component-tester/issues/2

## bower dependency
```javascript
  "web-component-tester": "t2ym/web-component-tester#disconnect-on-drain"
```
