### ISSUE TITLE
Error: Unknown node type AssignmentPattern

### ISSUE THREAD

**Issue by t2ym** [t2ym/thin-hook#7]
Error: Unknown node type AssignmentPattern

### Root Cause:
`escodegen` depends on old `estraverse`

```
Error: Unknown node type AssignmentPattern.
    at Controller.traverse (/home/fedora/WebComponents/components/thin-hook/node_modules/estraverse/estraverse.js:517:31)
    at traverse (/home/fedora/WebComponents/components/thin-hook/node_modules/estraverse/estraverse.js:709:27)
    at Object.attachComments (/home/fedora/WebComponents/components/thin-hook/node_modules/estraverse/estraverse.js:798:9)
    at Object.preprocess (/home/fedora/WebComponents/components/thin-hook/hook.js:144:35)
    at Object.<anonymous> (/home/fedora/WebComponents/components/thin-hook/hook-cli.js:15:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

**Comment by t2ym** [comment]
`escodegen` package has to be updated from the latest `t2ym/escodegen#master`, which depends on `estraverse#^4.2.0`
